version: '3.8'

services:
  backend:
    image: admin2906/mern-backend:1.0
    container_name: hub-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://dinhlamtq2000_db_user:1234567890@ac-4ilbgqg-shard-00-00.2cwmdx9.mongodb.net:27017,ac-4ilbgqg-shard-00-01.2cwmdx9.mongodb.net:27017,ac-4ilbgqg-shard-00-02.2cwmdx9.mongodb.net:27017/?tls=true&authSource=admin&replicaSet=atlas-akc5fc-shard-0&retryWrites=true&w=majority

  frontend:
    image: admin2906/mern-frontend:2.0
    container_name: hub-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend